export const showcaseSites = [
  {
    id: "sg-saas-001",
    title: "Bright SaaS Starter",
    template: "AI SaaS Website",
    tags: ["SaaS", "Bright", "Premium"],
    outcome: "Hero rhythm + proof + pricing + FAQ",
    accent: "blue",
    href: "/p/new",
  },
  {
    id: "sg-local-002",
    title: "Local Service High-Trust",
    template: "Local Service",
    tags: ["Local", "Trust", "Conversion"],
    outcome: "Trust-first layout with reviews and clear CTAs",
    accent: "emerald",
    href: "/p/new",
  },
  {
    id: "sg-portfolio-003",
    title: "Creator Portfolio",
    template: "Creator / Portfolio",
    tags: ["Creator", "Showcase", "Clean"],
    outcome: "Gallery + case studies + social proof",
    accent: "indigo",
    href: "/p/new",
  },
  {
    id: "sg-product-004",
    title: "Product Landing Pro",
    template: "Product Landing",
    tags: ["Product", "Comparison", "Launch"],
    outcome: "Benefits → comparison → proof → CTA ladder",
    accent: "slate",
    href: "/p/new",
  },
  {
    id: "sg-agency-005",
    title: "Agency Packages",
    template: "Agency",
    tags: ["Agency", "B2B", "Packages"],
    outcome: "Services + proof + process + packages",
    accent: "blue",
    href: "/p/new",
  },
  {
    id: "sg-comingsoon-006",
    title: "Coming Soon Waitlist",
    template: "Coming Soon",
    tags: ["Launch", "Waitlist", "Simple"],
    outcome: "Fast waitlist conversion page with proof",
    accent: "emerald",
    href: "/p/new",
  },
  {
    id: "sg-saas-007",
    title: "SaaS Pricing Focus",
    template: "AI SaaS Website",
    tags: ["SaaS", "Pricing", "Clarity"],
    outcome: "Pricing-first layout with comparison & FAQs",
    accent: "indigo",
    href: "/p/new",
  },
  {
    id: "sg-local-008",
    title: "Trades & Services",
    template: "Local Service",
    tags: ["Local", "Bookings", "Trust"],
    outcome: "Areas served + outcomes + contact flow",
    accent: "slate",
    href: "/p/new",
  },
  {
    id: "sg-portfolio-009",
    title: "Case Study Showcase",
    template: "Creator / Portfolio",
    tags: ["Portfolio", "Case Studies", "Premium"],
    outcome: "Case-study driven layout for credibility",
    accent: "blue",
    href: "/p/new",
  },
  {
    id: "sg-product-010",
    title: "Feature-led Launch",
    template: "Product Landing",
    tags: ["Launch", "Features", "Proof"],
    outcome: "Features grid + proof strip + CTA ladder",
    accent: "emerald",
    href: "/p/new",
  },
  {
    id: "sg-agency-011",
    title: "Consulting Offer",
    template: "Agency",
    tags: ["B2B", "Offer", "Trust"],
    outcome: "Offer clarity + proof + consultation CTA",
    accent: "indigo",
    href: "/p/new",
  },
  {
    id: "sg-saas-012",
    title: "Modern SaaS Minimal",
    template: "AI SaaS Website",
    tags: ["SaaS", "Minimal", "Clean"],
    outcome: "Minimal hero with strong hierarchy and rhythm",
    accent: "slate",
    href: "/p/new",
  },
];
