import { nowIso, slugify, toTitle } from "./utils";

export type MarketingPageSpec = {
  slug: string;
  title: string;
  description: string;
  sections: Array<{ type: string; heading?: string; body?: string }>;
  generatedAt: string;
};

export function generateMarketingPageSpec(input: {
  slug?: string;
  title?: string;
  description?: string;
}): MarketingPageSpec {
  const slug = slugify(input.slug || input.title || "page");
  const title = input.title || toTitle(slug);
  const description =
    input.description ||
    "Autogenerated placeholder content (safe stub). Replace with real generator when ready.";

  return {
    slug,
    title,
    description,
    sections: [
      { type: "hero", heading: title, body: description },
      { type: "proof", heading: "Proof", body: "Before / After / Spec (stub-safe until wired)." },
      { type: "cta", heading: "Try Dominat8", body: "Generate a site, refine, SEO, publish." }
    ],
    generatedAt: nowIso()
  };
}
/**
 * Compatibility export: store.ts expects generateContentForCampaign().
 * Returns deterministic, stub-safe content for build + dry-run.
 */
export type CampaignInput = {
  campaignId?: string;
  topic?: string;
  intent?: string;
  slugs?: string[];
};

export type GeneratedContentItem = {
  slug: string;
  title: string;
  description: string;
  html: string;
  spec: MarketingPageSpec;
};

export async function generateContentForCampaign(input: any, platform?: any): Promise<any> {
  // Build-safe, permissive stub:
  // - accepts (input, platform?) to match store.ts callsites
  // - returns deterministic items so TS/lint/build can proceed
  const topic = (input && (input.topic || input.name || input.title))
    ? String(input.topic || input.name || input.title)
    : "wow-website-builder";

  const slugs = (input && Array.isArray(input.slugs) && input.slugs.length)
    ? input.slugs.map((s: any) => String(s))
    : [topic, "templates", "use-cases"].map((s) =>
        String(s)
          .toLowerCase()
          .trim()
          .replace(/[^a-z0-9]+/g, "-")
          .replace(/^-+|-+$/g, "")
      );

  const items = slugs.map((slug: string) => {
    const title = slug
      .replace(/-/g, " ")
      .replace(/\b\w/g, (m) => m.toUpperCase());

    const description = (input && input.topic)
      ? `Campaign (stub) for: ${String(input.topic)}`
      : "Campaign stub content (build-safe).";

    const html = `
      <main style="font-family:system-ui;padding:40px;max-width:900px;margin:0 auto;">
        <h1>${title}</h1>
        <p>${description}</p>
        <hr />
        <p><strong>Note:</strong> Deterministic stub output (build-safe).</p>
      </main>
    `.trim();

    return { slug, title, description, html, spec: { slug, title, description } };
  });

  return items;
}